# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b83a86f070012081aa31a8a97b45d3ea5cfc792241ed867b19b264b0b919bbba82a0f9e211876c4debb78e7c5066411b199b6ea8c12a9f34dd9f3822a10c3bec

test:
  secret_key_base: 4d247fbf4cc13ecbfd95fd530ed115c1c534a65b2253f6fff3a580673a13eae97bfcdb952227d2415f7aa20eb738b2a11e7c90ac19f7216bcba7c94c253fe4be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
